### ISSUE TITLE
Upload to codecov.io only from master

### ISSUE THREAD

**Issue by avishayp** [ProjectDrawdown/solutions#45]
Running the `Export to codecov.io` workflow step depends on secret. Skipping this step on feature branches will allow external contributors to submit greenish PRs.

At this stage an `if` directive may suffice.
```
    - name: Export to codecov.io
      uses: codecov/codecov-action@v1.0.2
      if: github.event_name == 'push' && github.ref == 'refs/heads/master'
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.xml
```

The more feature-complete and verbose way is having two workflow files with branch filter directives.
